# This is a repository_dispatch workflow that will be generate a Solace PubSub+ Event Portal Implementation file given an AsyncAPI file

# how to test this workflow from another workflow

# run: |
#       spec=`cat $ASYNCAPI_FILE_PATH | base64`
#       curl -X POST -u "${{ github.actor }}:${{ secrets.WORKFLOW_PAT }}" \
#         -H "Accept: application/vnd.github.everest-preview+json"  \
#         -H "Content-Type: application/json" \
#         https://api.github.com/repos/${{ secrets.INFRA_REPO }}/dispatches \
#         --data "{\"event_type\":\"trigger-event\",\"client_payload\":{\"asyncapi\":\"$spec\"}}"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# WORKFLOW_PAT: Personal Access Token token for the destination repo for authentication. See more here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
## Note: The PAT should have workflow access enabled

name: generate-implementation-configuration

on:
  repository_dispatch:
    types: ["trigger-event"]


env:
  SPEC: ${{ github.event.client_payload.asyncapi }}

jobs:
  generate-implementation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'      

      - name: Run generate implementation script with AsyncAPI spec as input parameter
        run: |
          cd scripts
          npm install
          node generate_implementation.js $SPEC

      - name: Commit implementation files back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Added implementation files for the following queues ${{env.QUEUES}}
          file_pattern: 'implementation/*'
          commit_user_name: Solace Bot